apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapidx-frontend
  labels:
    app: rapidx-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rapidx-frontend
  template:
    metadata:
      labels:
        app: rapidx-frontend
    spec:
      containers:
        - name: frontend
          # Replace with your own Docker Hub username if different
          image: muhammadsohaibriaz/rapidx-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: rapidx-config
                  key: NEXT_PUBLIC_API_BASE_URL
            - name: NEXT_PUBLIC_SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rapidx-secrets
                  key: supabase-url
            - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: rapidx-secrets
                  key: supabase-anon-key
---
apiVersion: v1
kind: Service
metadata:
  name: rapidx-frontend
  labels:
    app: rapidx-frontend
spec:
  type: LoadBalancer
  selector:
    app: rapidx-frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
